.PHONY: all
all:
	$(MAKE) -j8 -C php\@7.1 $@
	$(MAKE) -j8 -C php\@7.2 $@
	$(MAKE) -j8 -C php\@7.3 $@
	$(MAKE) -j8 -C php\@7.4 $@

.PHONY: clean
clean:
	$(MAKE) -j8 -C php\@7.1 $@
	$(MAKE) -j8 -C php\@7.2 $@
	$(MAKE) -j8 -C php\@7.3 $@
	$(MAKE) -j8 -C php\@7.4 $@
